require("tom.plugins-setup")
require("tom.core.options")
require("tom.core.keymaps")
require("tom.core.colorscheme")
require("tom.plugins.comment")
require("tom.plugins.nvim-tree")
require("tom.plugins.lualine")
require("tom.plugins.telescope")
require("tom.plugins.nvim-cmp")
require("tom.plugins.lsp.mason")
require("tom.plugins.lsp.lspsaga")
require("tom.plugins.lsp.lspconfig")
require("tom.plugins.lsp.null-ls")
require("tom.plugins.autopairs")
require("tom.plugins.treesitter")
require("tom.plugins.gitsigns")

